### ISSUE TITLE
@Mention

### ISSUE THREAD

**Issue by osakiy** [FreEZer00/teams-webhook-action#229]
Hi.

I like this workflow. I have one question.
How do you sent @mention in message?

We can sent message with mention using adaptive card like that.

```
$ curl -X POST ${WEBHOOK} -H "Content-Type: application/json" -d @sample.json
```

https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cdesktop%2Cconnector-html#sample-adaptive-card-with-a-mention

If it is possible, let me know. Thanks.

**Comment by FreEZer00** [comment]
Hi @osakiy 
thank you for the feedback. 
unfortunately he type of message produced by this action is a Messagecard and not and adpative card

https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL

I could not find any resources that would allow a mention inside of a MessageCard. If you find anything feel free to let me know

**Comment by osakiy** [comment]
@FreEZer00 

Thanks for your reply.
I got it the difference between Message card and Adaptive card.

Thanks.
